from sklearn.neighbors import KernelDensity
from sklearn.datasets import load_digits
from matplotlib import pyplot as plt
import random

# load the hand-written digets dataset
X, y = load_digits(return_X_y=True)


# plot some digits chosen at random from the set
fig, ax = plt.subplots(4, 4)
for i in range(4):
    for j in range(4):
        img_idx = random.randint(0, len(X))
        ax[i][j].imshow(X[img_idx].reshape((8,8)), cmap='binary')
plt.suptitle('some images from the dataset')
plt.show()


# fit a KDE to the images (in X)
kde = KernelDensity(bandwidth = 0.1)
kde.fit(X)


# plot more images - this time randomly generated by the KDE
fig, ax = plt.subplots(4, 4)
for i in range(4):
    for j in range(4):
        img_idx = random.randint(0, len(X))
        ax[i][j].imshow(kde.sample().reshape((8,8)), cmap='binary')
plt.suptitle('random images from the KDE')
plt.show()